spring.datasource.url=jdbc:postgresql://localhost:5432/control_academico
spring.datasource.username=postgres
spring.datasource.password=Matias123
# update: si ya existe tabla, Hibernate intentará mantener estructura
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true